language: r
sudo: false
cache: packages
env:
  global:
  - secure: q+7jvDTgGBFt/QgCFwyqlq80dEIPq8BaAf1oIAZRSrdeZvkfXxI7MbbBG2V08zPQwm3/DE7OHQlkOUJDZs8ed07VMB1LfFXP3B/eVITx6kvSEQ0jJevnU85Hs2FZ53OtVLQ1X08qgRl/mjTGq8MfrrlAOXWoa66XTNKcpNPhpT1jMhPr/sjuuz3nk2eSU7K7Rssx/BqOJeKOXSUyFWIBQnzo9gbJI53CX+GLkpmOCM+K7aaVtnhXynFq/0eeEDO7/hywabLom4rKREhVrwjr6KhBwv2Qgkx3N/u5XAjUUMvMxji9kk/ircz6LZIkkrVc7rOagLrrxTdaDOVrk+pX6mwab4Z0Z7g4C3GyhymWM0w9rfYjLvlPMf3eJU3+OrL7UhMBmTl2YJ+/9xYhN4bTuI1RnP+087waE0DRerMTFBMdIVj0vj5n31qp6KZIKo9gcfgDx4fHHrGndCkBjxfX603ACc7MmaizYGXZPAKs3EOZSXIVItkLsotegp38RDWea3WymFjHaZ05hxL6wQDoGqjj4eCERkbi00Pj32Ga7tv6rhFL1CVPCPXjREkd/0gwc1J8UuT2vkbc2tJ9w0YlAaSsJQs+LXrVXYXsnFjulOeF/sPMeC09j4SARdIYOvXpxeBQ5upAibO9ZQ4O4SiruMTtJz0WOk0oq9mY/T1B0JE=
r_github_packages:
- rstudio/rmarkdown
install:
- R -e "install.packages('devtools')"
- R -e "devtools::install_github('rstudio/rmarkdown')"
- wget https://github.com/mathjax/MathJax/archive/master.zip
- unzip master.zip >/dev/null
- rm master.zip
- export RMARKDOWN_MATHJAX_PATH=$PWD/MathJax-master
script:
- R -e "rmarkdown::render_site()"
- tools/pdf_all
- tools/headers
after_success:
- ./tools/deploy.sh
